// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrNgxr5ANg7aNxHFsik6Ee8GKCXjDteVA',
    appId: '1:130186984850:web:1361d079c3f8be657e954b',
    messagingSenderId: '130186984850',
    projectId: 'weather-app-3989a',
    authDomain: 'weather-app-3989a.firebaseapp.com',
    storageBucket: 'weather-app-3989a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHo67MhU9--alWIiIQc5E__ZiLRJ70mfI',
    appId: '1:130186984850:android:40bc8b6ea080a4557e954b',
    messagingSenderId: '130186984850',
    projectId: 'weather-app-3989a',
    storageBucket: 'weather-app-3989a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuY5RhPnnw29WL7DTQWw02ZB3kqel18sQ',
    appId: '1:130186984850:ios:10b7c1f9e995fcd67e954b',
    messagingSenderId: '130186984850',
    projectId: 'weather-app-3989a',
    storageBucket: 'weather-app-3989a.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuY5RhPnnw29WL7DTQWw02ZB3kqel18sQ',
    appId: '1:130186984850:ios:10b7c1f9e995fcd67e954b',
    messagingSenderId: '130186984850',
    projectId: 'weather-app-3989a',
    storageBucket: 'weather-app-3989a.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrNgxr5ANg7aNxHFsik6Ee8GKCXjDteVA',
    appId: '1:130186984850:web:1488f4c0df63bfec7e954b',
    messagingSenderId: '130186984850',
    projectId: 'weather-app-3989a',
    authDomain: 'weather-app-3989a.firebaseapp.com',
    storageBucket: 'weather-app-3989a.firebasestorage.app',
  );
}
