const List<String> cities = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'San Francisco',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington D.C.',
  'Boston',
  'El Paso',
  'Detroit',
  'Nashville',
  'Portland',
  'Las Vegas',
  'Memphis',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Mesa',
  'Atlanta',
  'Kansas City',
  'Colorado Springs',
  'Miami',
  'Raleigh',
  'Omaha',
  'Long Beach',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Tampa',
  'Arlington',
  'New Orleans',
  'Wichita',
  'Cleveland',
  'Bakersfield',
  'Aurora',
  'Anaheim',
  'Honolulu',
  'Santa Ana',
  'Riverside',
  'Corpus Christi',
  'Lexington',
  'Stockton',
  'Henderson',
  'Saint Paul',
  'St. Louis',
  'Cincinnati',
  'Pittsburgh',
  'Greensboro',
  'Anchorage',
  'Plano',
  'Lincoln',
  'Orlando',
  'Irvine',
  'Newark',
  'Toledo',
  'Durham',
  'Chula Vista',
  'Fort Wayne',
  'Jersey City',
  'St. Petersburg',
  'Laredo',
  'Madison',
  'Chandler',
  'Buffalo',
  'Lubbock',
  'Scottsdale',
  'Reno',
  'Glendale',
  'Gilbert',
  'Winston-Salem',
  'North Las Vegas',
  'Norfolk',
  'Chesapeake',
  'Garland',
  'Irving',
  'Hialeah',
  'Fremont',
  'Boise',
  'Richmond',
  'Spokane',
  'Baton Rouge',
  'Tacoma',
  'Cairo',
  'San Bernardino',
  'Oxnard',
  'Fontana',
  'Moreno Valley',
  'Santa Clara',
  'Salt Lake City',
  'Newport Beach',
  'Lancaster',
  'Lakewood',
  'Huntington Beach',
  'Tempe',
  'Sunnyvale',
  'Santa Cruz',
  'Simi Valley',
  'Santa Rosa',
  'Salem',
  'San Mateo',
  'Santa Monica',
  'Redding',
  'San Leandro',
  'London',
  'Paris',
  "Madrid",
  "Berlin",
  'Tokyo',
  'Moscow',
  'Macca',
  'Riyadh',
  'Dubai',
  'Abu Dhabi',
  'Sharjah'
];

const String kCurrentLocation = 'Current Location';
